export {
  // Constants
  ASSUMPTION_DISCIPLINE_PROMPT,

  // Enums / Schemas
  DocumentStatusSchema,
  FlagSeveritySchema,
  RiskSeveritySchema,
  RiskLikelihoodSchema,
  MoSCoWPrioritySchema,
  QuestionStatusSchema,

  // Sub-schemas
  AgentFlagSchema,
  ClarifyingQuestionSchema,
  ProblemSectionSchema,
  ContextDimensionSchema,
  ContextSectionSchema,
  GoalSchema,
  AlternativeApproachSchema,
  TechnicalPatternSchema,
  KnownPitfallSchema,
  PriorArtSchema,
  ResearchSectionSchema,
  FunctionalRequirementSchema,
  NonFunctionalRequirementSchema,
  ScaleProfileSchema,
  RequirementsSectionSchema,
  RiskSchema,
  OpenQuestionSchema,
  DecisionLogEntrySchema,
  MetadataSchema,
  DiscoveryDocumentSchema,

  // Types
  type DocumentStatus,
  type FlagSeverity,
  type RiskSeverity,
  type RiskLikelihood,
  type MoSCoWPriority,
  type QuestionStatus,
  type AgentFlag,
  type ClarifyingQuestion,
  type ProblemSection,
  type ContextDimension,
  type ContextSection,
  type Goal,
  type AlternativeApproach,
  type TechnicalPattern,
  type KnownPitfall,
  type PriorArt,
  type ResearchSection,
  type FunctionalRequirement,
  type NonFunctionalRequirement,
  type ScaleProfile,
  type RequirementsSection,
  type Risk,
  type OpenQuestion,
  type DecisionLogEntry,
  type Metadata,
  type DiscoveryDocument,
  type DocumentHealth,

  // Functions
  parseDiscoveryDocument,
  safeParseDiscoveryDocument,
  validateReadyForSystem2,
  computeRiskScore,
  extractAssumedFields,
  createNewVersion,
  getDocumentHealth,
} from "./discovery-document.ts";
